const artObjectsList = {
  "data": [
    {
      "image": "assets/unsplash-1.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "space",
      "objectNumber": null,
      "title": "Space",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 27,
      "materials": [],
      "techniques": "Pottery"
    },
    {
      "image": "assets/unsplash-2.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "art",
      "objectNumber": null,
      "title": "Art",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 28,
      "materials": [],
      "techniques": "Islamic Art"
    },
    {
      "image": "assets/unsplash-3.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "marie-bonaparte-s-tiara",
      "objectNumber": null,
      "title": "Marie Bonaparte’s Tiara",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 1,
      "materials": [],
      "techniques": "Tapestry"
    },
    {
      "image": "assets/unsplash-4.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "sample-of-iraqi-soil-excavation-5-layers-of-death",
      "objectNumber": null,
      "title": "Sample of Iraqi Soil Excavation = 5 Layers of Death",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 2,
      "materials": [],
      "techniques": "Glass"
    },
    {
      "image": "assets/unsplash-5.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "architectural-wall-decoration",
      "objectNumber": null,
      "title": "Architectural Wall Decoration",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 3,
      "materials": [],
      "techniques": "Pottery"
    },
    {
      "image": "assets/unsplash-6.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "composition",
      "objectNumber": null,
      "title": "Composition",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 4,
      "materials": [],
      "techniques": "Islamic Art"
    },
    {
      "image": "assets/unsplash-7.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "bowl",
      "objectNumber": null,
      "title": "Bowl",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 5,
      "materials": [],
      "techniques": "Tapestry"
    },
    {
      "image": "assets/unsplash-8.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "ayuba-suleiman-diallo-job-ben-solomon",
      "objectNumber": null,
      "title": "Ayuba Suleiman Diallo, Job ben Solomon",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 7,
      "materials": [],
      "techniques": "Glass"
    },
    {
      "image": "assets/unsplash-9.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "portrait-of-mrs-easter-menasha",
      "objectNumber": null,
      "title": "Portrait of Mrs. Easter Menasha",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 8,
      "materials": [],
      "techniques": "Pottery"
    },
    {
      "image": "assets/unsplash-1.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "space",
      "objectNumber": null,
      "title": "Space",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 27,
      "materials": [],
      "techniques": "Pottery"
    },
    {
      "image": "assets/unsplash-2.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "art",
      "objectNumber": null,
      "title": "Art",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 28,
      "materials": [],
      "techniques": "Islamic Art"
    },
    {
      "image": "assets/unsplash-3.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "marie-bonaparte-s-tiara",
      "objectNumber": null,
      "title": "Marie Bonaparte’s Tiara",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 1,
      "materials": [],
      "techniques": "Tapestry"
    },
    {
      "image": "assets/unsplash-4.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "sample-of-iraqi-soil-excavation-5-layers-of-death",
      "objectNumber": null,
      "title": "Sample of Iraqi Soil Excavation = 5 Layers of Death",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 2,
      "materials": [],
      "techniques": "Glass"
    },
    {
      "image": "assets/unsplash-5.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "architectural-wall-decoration",
      "objectNumber": null,
      "title": "Architectural Wall Decoration",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 3,
      "materials": [],
      "techniques": "Pottery"
    },
    {
      "image": "assets/unsplash-6.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "composition",
      "objectNumber": null,
      "title": "Composition",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 4,
      "materials": [],
      "techniques": "Islamic Art"
    },
    {
      "image": "assets/unsplash-7.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "bowl",
      "objectNumber": null,
      "title": "Bowl",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 5,
      "materials": [],
      "techniques": "Tapestry"
    },
    {
      "image": "assets/unsplash-8.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "ayuba-suleiman-diallo-job-ben-solomon",
      "objectNumber": null,
      "title": "Ayuba Suleiman Diallo, Job ben Solomon",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 7,
      "materials": [],
      "techniques": "Glass"
    },
    {
      "image": "assets/unsplash-9.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "portrait-of-mrs-easter-menasha",
      "objectNumber": null,
      "title": "Portrait of Mrs. Easter Menasha",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 8,
      "materials": [],
      "techniques": "Pottery"
    },
    {
      "image": "assets/unsplash-1.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "space",
      "objectNumber": null,
      "title": "Space",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 27,
      "materials": [],
      "techniques": "Pottery"
    },
    {
      "image": "assets/unsplash-2.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "art",
      "objectNumber": null,
      "title": "Art",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 28,
      "materials": [],
      "techniques": "Islamic Art"
    },
    {
      "image": "assets/unsplash-3.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "marie-bonaparte-s-tiara",
      "objectNumber": null,
      "title": "Marie Bonaparte’s Tiara",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 1,
      "materials": [],
      "techniques": "Tapestry"
    },
    {
      "image": "assets/unsplash-4.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "sample-of-iraqi-soil-excavation-5-layers-of-death",
      "objectNumber": null,
      "title": "Sample of Iraqi Soil Excavation = 5 Layers of Death",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 2,
      "materials": [],
      "techniques": "Glass"
    },
    {
      "image": "assets/unsplash-5.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "architectural-wall-decoration",
      "objectNumber": null,
      "title": "Architectural Wall Decoration",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 3,
      "materials": [],
      "techniques": "Pottery"
    },
    {
      "image": "assets/unsplash-6.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "composition",
      "objectNumber": null,
      "title": "Composition",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 4,
      "materials": [],
      "techniques": "Islamic Art"
    },
    {
      "image": "assets/unsplash-7.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "bowl",
      "objectNumber": null,
      "title": "Bowl",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 5,
      "materials": [],
      "techniques": "Tapestry"
    },
    {
      "image": "assets/unsplash-8.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "ayuba-suleiman-diallo-job-ben-solomon",
      "objectNumber": null,
      "title": "Ayuba Suleiman Diallo, Job ben Solomon",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 7,
      "materials": [],
      "techniques": "Glass"
    },
    {
      "image": "assets/unsplash-9.jpg",
      "displayDate": null,
      "productionCulturalGroup": null,
      "site": null,
      "recordType": null,
      "objectName": null,
      "slug": "portrait-of-mrs-easter-menasha",
      "objectNumber": null,
      "title": "Portrait of Mrs. Easter Menasha",
      "location": null,
      "styles": null,
      "artist": null,
      "museum": null,
      "sort": null,
      "id": 8,
      "materials": [],
      "techniques": "Pottery"
    }
  ]
}

let gallery = document.querySelector(".gallery");

function generateGallery() {
  artObjectsList.data.forEach(element => {
    let item = generateImage('#', element.image, element.title, element.techniques);
    gallery.appendChild(item);
  });
}

function generateImage(link, source, altText, category) {
  let listItem = document.createElement('li');
  let anchor = document.createElement('a');
  let image = document.createElement('img');

  anchor.setAttribute('href', link);
  anchor.setAttribute('aria-label', "details");

  image.setAttribute('width', '250');
  image.setAttribute('src', source);
  image.setAttribute('alt', altText);
  image.setAttribute('data-category', category);

  anchor.appendChild(image);
  listItem.appendChild(anchor);
  return listItem;
}

generateGallery();

window.addEventListener("scroll", function () {
  if (window.innerHeight + window.scrollY >= document.body.offsetHeight) {
    generateGallery();
  }
});
